// 1
create or replace package pakiet_zajecia as
    procedure add_row_to_jobs(
        j_id    in jobs.job_id%type,
        j_title in jobs.job_title%type
    );

    procedure get_employee_by_id(
        p_employee_id in employees.employee_id%type
    );

    function get_job_by_id(
        f_job_id in jobs.job_id%type
    ) return jobs.job_title%type;

    function get_employee_year_salary(
        f_employee_id in employees.employee_id%type
    ) return number;

end pakiet_zajecia;
/

create or replace package body pakiet_zajecia as
    procedure add_row_to_jobs(
        j_id    in jobs.job_id%type,
        j_title in jobs.job_title%type
    ) is
    begin
        insert into jobs (job_id, job_title)
        values (j_id, j_title);
    exception
        when dup_val_on_index then
            dbms_output.put_line('Duplicated value');
    end;


    procedure get_employee_by_id(
        p_employee_id in employees.employee_id%type
    ) is
        v_last_name employees.last_name%type;
        v_salary    employees.salary%type;
    begin
        select last_name, salary
        into v_last_name, v_salary
        from employees
        where employee_id = p_employee_id;

        dbms_output.put_line(
            'Employee: ' || v_last_name || ', Salary: ' || v_salary
        );
    exception
        when no_data_found then
            dbms_output.put_line('Employee not found');
    end;


    function get_job_by_id(
        f_job_id in jobs.job_id%type
    ) return jobs.job_title%type is
        v_job_title jobs.job_title%type;
    begin
        select job_title
        into v_job_title
        from jobs
        where job_id = f_job_id;

        return v_job_title;
    exception
        when no_data_found then
            return null;
    end;


    function get_employee_year_salary(
        f_employee_id in employees.employee_id%type
    ) return number is
        v_year_salary number;
    begin
        select (salary + salary * nvl(commission_pct, 0)) * 12
        into v_year_salary
        from employees
        where employee_id = f_employee_id;

        return v_year_salary;
    exception
        when no_data_found then
            return null;
    end;

end pakiet_zajecia;
/

// 2
create or replace package crud_regions is
    type t_region_rec is record (
        region_id   regions.region_id%type,
        region_name regions.region_name%type
    );

    type t_region_tab is table of t_region_rec;

    procedure create_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    );

    function get_region_name (
        p_region_id in regions.region_id%type
    ) return regions.region_name%type;

    procedure get_all_regions (
        p_regions out t_region_tab
    );

    procedure update_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    );

    procedure delete_region (
        p_region_id in regions.region_id%type
    );

end crud_regions;
/

create or replace package body crud_regions is
    procedure create_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    ) is
    begin
        insert into regions (region_id, region_name)
        values (p_region_id, p_region_name);
    end create_region;

    function get_region_name (
        p_region_id in regions.region_id%type
    ) return regions.region_name%type is
        v_region_name regions.region_name%type;
    begin
        select region_name
        into   v_region_name
        from   regions
        where  region_id = p_region_id;

        return v_region_name;
    exception
        when no_data_found then
            return null;
    end get_region_name;

    procedure get_all_regions (
        p_regions out t_region_tab
    ) is
    begin
        select region_id, region_name
        bulk collect into p_regions
        from regions
        order by region_id;
    end get_all_regions;

    procedure update_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    ) is
    begin
        update regions
        set    region_name = p_region_name
        where  region_id   = p_region_id;
    end update_region;

    procedure delete_region (
        p_region_id in regions.region_id%type
    ) is
    begin
        delete from regions
        where  region_id = p_region_id;
    end delete_region;

end crud_regions;
/

// 3
create table regions_audit_log (
    log_id        number generated by default as identity primary key,
    log_date      date        default sysdate,
    operation     varchar2(30),
    region_id     number,
    error_code    number,
    error_message varchar2(4000)
);

create or replace package crud_regions is
    type t_region_rec is record (
        region_id   regions.region_id%type,
        region_name regions.region_name%type
    );

    type t_region_tab is table of t_region_rec;

    e_region_name_exists exception;
    e_region_has_countries exception;

    pragma exception_init(e_region_name_exists,  -20001);
    pragma exception_init(e_region_has_countries, -20002);

    procedure create_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    );

    procedure get_all_regions (
        p_regions out t_region_tab
    );

    procedure update_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    );

    procedure delete_region (
        p_region_id in regions.region_id%type
    );

end crud_regions;
/

create or replace package body crud_regions is
    procedure log_error (
        p_operation     in varchar2,
        p_region_id     in number,
        p_error_code    in number,
        p_error_message in varchar2
    ) is
    begin
        insert into regions_audit_log (
            operation,
            region_id,
            error_code,
            error_message
        ) values (
            p_operation,
            p_region_id,
            p_error_code,
            p_error_message
        );
    end log_error;

    procedure create_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    ) is
        v_cnt number;
    begin
        select count(*)
        into   v_cnt
        from   regions
        where  upper(region_name) = upper(p_region_name);

        if v_cnt > 0 then
            raise_application_error(
                -20001,
                'Region o podanej nazwie już istnieje'
            );
        end if;

        insert into regions (region_id, region_name)
        values (p_region_id, p_region_name);

    exception
        when others then
            log_error(
                'CREATE',
                p_region_id,
                sqlcode,
                sqlerrm
            );
            raise;
    end create_region;

    procedure get_all_regions (
        p_regions out t_region_tab
    ) is
    begin
        select region_id, region_name
        bulk collect into p_regions
        from regions
        order by region_id;
    end get_all_regions;

    procedure update_region (
        p_region_id   in regions.region_id%type,
        p_region_name in regions.region_name%type
    ) is
    begin
        update regions
        set    region_name = p_region_name
        where  region_id   = p_region_id;

    exception
        when others then
            log_error(
                'UPDATE',
                p_region_id,
                sqlcode,
                sqlerrm
            );
            raise;
    end update_region;

    procedure delete_region (
        p_region_id in regions.region_id%type
    ) is
        v_cnt number;
    begin
        select count(*)
        into   v_cnt
        from   countries
        where  region_id = p_region_id;

        if v_cnt > 0 then
            raise_application_error(
                -20002,
                'Nie można usunąć regionu z przypisanymi krajami'
            );
        end if;

        delete from regions
        where  region_id = p_region_id;

    exception
        when others then
            log_error(
                'DELETE',
                p_region_id,
                sqlcode,
                sqlerrm
            );
            raise;
    end delete_region;

end crud_regions;
/

// 4 
create or replace package dept_statistics is
    function avg_salary_by_department (
        p_department_id in departments.department_id%type
    ) return number;

    function min_salary_by_job (
        p_job_id in jobs.job_id%type
    ) return number;

    function max_salary_by_job (
        p_job_id in jobs.job_id%type
    ) return number;

    procedure generate_text_report (
        p_department_id in departments.department_id%type
    );

end dept_statistics;
/

create or replace package body dept_statistics is
    function avg_salary_by_department (
        p_department_id in departments.department_id%type
    ) return number is
        v_avg_salary number;
    begin
        select avg(salary)
        into   v_avg_salary
        from   employees
        where  department_id = p_department_id;

        return v_avg_salary;
    end avg_salary_by_department;

    function min_salary_by_job (
        p_job_id in jobs.job_id%type
    ) return number is
        v_min_salary number;
    begin
        select min(salary)
        into   v_min_salary
        from   employees
        where  job_id = p_job_id;

        return v_min_salary;
    end min_salary_by_job;

    function max_salary_by_job (
        p_job_id in jobs.job_id%type
    ) return number is
        v_max_salary number;
    begin
        select max(salary)
        into   v_max_salary
        from   employees
        where  job_id = p_job_id;

        return v_max_salary;
    end max_salary_by_job;

    procedure generate_text_report (
        p_department_id in departments.department_id%type
    ) is
        v_dept_name departments.department_name%type;
        v_avg_sal   number;
    begin
        select department_name
        into   v_dept_name
        from   departments
        where  department_id = p_department_id;

        v_avg_sal := avg_salary_by_department(p_department_id);

        dbms_output.put_line('======================================');
        dbms_output.put_line('RAPORT STATYSTYCZNY DEPARTAMENTU');
        dbms_output.put_line('ID DEPARTAMENTU : ' || p_department_id);
        dbms_output.put_line('NAZWA           : ' || v_dept_name);
        dbms_output.put_line('ŚREDNIA PENSJA  : ' || round(v_avg_sal, 2));
        dbms_output.put_line('======================================');
        dbms_output.put_line('STANOWISKA:');

        for r in (
            select j.job_title,
                   min(e.salary) min_sal,
                   max(e.salary) max_sal
            from   employees e
            join   jobs j on j.job_id = e.job_id
            where  e.department_id = p_department_id
            group by j.job_title
            order by j.job_title
        ) loop
            dbms_output.put_line(
                rpad(r.job_title, 30) ||
                ' MIN: ' || r.min_sal ||
                ' MAX: ' || r.max_sal
            );
        end loop;

    exception
        when no_data_found then
            dbms_output.put_line('Brak danych dla podanego departamentu');
    end generate_text_report;

end dept_statistics;
/

// 5
create or replace package data_validation is

    procedure normalize_phone_numbers;

    procedure increase_salary_by_job (
        p_job_id     in jobs.job_id%type,
        p_percentage in number
    );

end data_validation;
/

create or replace package body data_validation is

    procedure normalize_phone_numbers is
        v_phone varchar2(50);
    begin
        for r in (
            select employee_id, phone_number
            from   employees
            where  phone_number is not null
        ) loop
            v_phone := regexp_replace(r.phone_number, '[^0-9]', '');

            if length(v_phone) = 9 then
                v_phone := '48' || v_phone;
            end if;

            v_phone :=
                '+' || substr(v_phone, 1, 2) || '-' ||
                substr(v_phone, 3, 3) || '-' ||
                substr(v_phone, 6, 3) || '-' ||
                substr(v_phone, 9, 3);

            update employees
            set    phone_number = v_phone
            where  employee_id  = r.employee_id;
        end loop;
    end normalize_phone_numbers;

    procedure increase_salary_by_job (
        p_job_id     in jobs.job_id%type,
        p_percentage in number
    ) is
    begin
        update employees
        set    salary = salary * (1 + p_percentage / 100)
        where  job_id = p_job_id;
    end increase_salary_by_job;

end data_validation;
/
