// 1
create table archiwum_departamentow (
    id number not null,
    nazwa varchar2(100) not null,
    data_zamkniecia date not null,
    ostatni_manager varchar2(200)
);

create or replace trigger trg_archiwum_departamentow
after delete on departments
for each row
declare
    v_ostatni_manager varchar2(200);
begin
    select e.first_name || ' ' || e.last_name
    into v_ostatni_manager
    from employees e
    where e.employee_id = :old.manager_id;
    
    insert into archiwum_departamentow (id, nazwa, data_zamkniecia, ostatni_manager)
    values (:old.department_id, :old.department_name, SYSDATE, v_ostatni_manager);
exception
    when no_data_found then
        insert into archiwum_departamentow (id, nazwa, data_zamkniecia, ostatni_manager)
        values (:old.department_id, :old.department_name, SYSDATE, null);
end;
/

delete from departments
where department_id = 270;

select * from archiwum_departamentow;

// 2
create table zlodziej (
    id number generated by default as identity,
    "user" varchar2(30),
    czas_zmiany date
);

create or replace trigger trg_salary_check
before insert or update of salary on employees
for each row
declare
    pragma autonomous_transaction;
begin
    if :new.salary < 2000 or :new.salary > 26000 then
        insert into zlodziej("user", czas_zmiany)
        values (user, sysdate);

        commit;

        raise_application_error(-20001, 'Wynagrodzenie nie miesci sie w widelkach 2000-26000');
    end if;
end;
/

insert into Employees (employee_id, first_name, last_name, email, hire_date, job_id, salary) 
    values (1001, 'Jan', 'Nowak', 'jan.nowak@email.com', DATE '2025-01-01', 'IT_PROG', 1000);
    
select * from zlodziej;

// 3
create sequence seq_employees_id
    start with 1
    increment by 1
    nocache
    nocycle;
    
create or replace trigger trg_employees_id
before insert on employees
for each row
begin
    if :new.employee_id is null then
        select seq_employees_id.nextval
        into :new.employee_id
        from dual;
    end if;
end;
/

insert into employees (
    first_name, last_name, email, hire_date, job_id
) values (
    'Jan', 'Kowalski', 'JKOWALSKI', sysdate, 'IT_PROG'
);

// 4
create or replace trigger trg_block_job_grades
before insert or update or delete on job_grades
begin
    raise_application_error(
        -20010,
        'Operacje INSERT, UPDATE i DELETE na tabeli JOB_GRADES są zabronione'
    );
end;
/

insert into job_grades values ('X', 1, 100);

update job_grades set min_salary = 1000;

delete from job_grades;

// 5
create or replace trigger trg_jobs_keep_salary
before update of min_salary, max_salary on jobs
for each row
begin
    :new.min_salary := :old.min_salary;
    :new.max_salary := :old.max_salary;
end;
/

update jobs
set min_salary = 100,
    max_salary = 50000
where job_id = 'IT_PROG';

select * from jobs
where job_id = 'IT_PROG';