------------------------------------------------------------------
-- TWORZENIE STRUKTURY BAZY --
------------------------------------------------------------------

------------------------------------------------------------------
-- tabele słownikowe
------------------------------------------------------------------
create table project_developers (
    developer_id number generated by default as identity primary key,
    name varchar2(255) not null unique,
    founded_year number(4)
        check (founded_year > 1800)
);

create table project_publishers (
    publisher_id number generated by default as identity primary key,
    name varchar2(255) not null unique,
    founded_year number(4)
        check (founded_year > 1800)
);

create table project_platforms (
    platform_id number generated by default as identity primary key,
    name varchar2(255) not null unique
);

create table project_categories (
    category_id number generated by default as identity primary key,
    name varchar2(255) not null unique
);

------------------------------------------------------------------
-- tabela główna
------------------------------------------------------------------
create table project_games (
    game_id number generated by default as identity primary key,
    title varchar2(255) not null,
    release_date date,
    rating number(3),
        check (rating between 0 and 100),
    developer_id number references project_developers(developer_id),
    publisher_id number references project_publishers(publisher_id),
    constraint project_uk_games unique (title, release_date)
);

------------------------------------------------------------------
-- tabela sprzedaży
------------------------------------------------------------------
create table project_sales (
    sale_id number generated by default as identity primary key,
    game_id number references project_games(game_id),
    region varchar2(50),
    units_sold number 
        check (units_sold >= 0),
    revenue number(12,2) check (revenue >= 0),
    sale_year number(4)
);

alter table project_sales
    add (sale_month number(2)
        check (sale_month between 1 and 12)
);

alter table project_sales modify (
    region not null,
    sale_year not null
);

alter table project_sales add constraint project_uk_sales
unique (game_id, region, sale_year, sale_month);


------------------------------------------------------------------
-- tabele relacji wiele do wielu
------------------------------------------------------------------
create table project_game_platforms (
    game_id number references project_games(game_id),
    platform_id number references project_platforms(platform_id),
    constraint project_pk_game_platforms primary key (game_id, platform_id)
);

create table project_game_categories (
    game_id number references project_games(game_id),
    category_id number references project_categories(category_id),
    constraint project_pk_game_categories primary key (game_id, category_id)
);

------------------------------------------------------------------
-- archiwizacja i logowanie
------------------------------------------------------------------
create table project_data_archive (
    archive_id number generated by default as identity primary key,
    source_type varchar2(20),
    source_name varchar2(255),
    raw_data clob check (raw_data is json),
    archived_at timestamp default systimestamp
);

create table project_load_logs (
    log_id number generated by default as identity primary key,
    event_time timestamp default systimestamp,
    event_type varchar2(20),
    message varchar2(4000)
);


------------------------------------------------------------------
-- tabela do zestawień rocznych/kwartalnych/miesięcznych
------------------------------------------------------------------
create table project_sales_summary (
    summary_id     number generated by default as identity primary key,
    period_type    varchar2(10) not null,  -- MONTH / QUARTER / YEAR
    period_year    number(4) not null,
    period_value   number not null,         -- miesiąc / kwartał / 0 dla roku
    game_id        number references project_games(game_id),
    region         varchar2(50),
    total_units    number,
    total_revenue  number(12,2),
    created_at     timestamp default systimestamp,

    constraint chk_period_type
        check (period_type in ('MONTH', 'QUARTER', 'YEAR'))
);

------------------------------------------------------------------
-- wprowadzanie danych z pliku .csv
------------------------------------------------------------------
create table project_games_stage (
    title         varchar2(255),
    release_date  varchar2(20),
    rating        number(3),
    developer     varchar2(255),
    publisher     varchar2(255),
    platform      varchar2(100),
    category      varchar2(100),
    region        varchar2(50),
    units_sold    number,
    revenue       number(12,2),
    sale_year     number(4)
);

alter table project_games_stage add (
    developer_founded_year number(4),
    publisher_founded_year number(4)
);

alter table project_games_stage add (
    sale_month number(2)
);

create or replace procedure project_load_games_etl is
    v_dev_id        project_developers.developer_id%type;
    v_pub_id        project_publishers.publisher_id%type;
    v_game_id       project_games.game_id%type;
    v_release_date  date;
    
    v_game_inserted     boolean := false;
    v_platform_inserted boolean := false;
    
    v_cnt_games_added number    := 0;
    v_cnt_games_existing number := 0;
    
    v_cnt_sales_added number    := 0;
    v_cnt_sales_existing number := 0;
    
    v_cnt_platforms_added number:= 0;
    
    v_cnt_warnings number := 0;
    v_cnt_errors   number := 0;
    
    v_error_msg varchar2(4000);
begin
    for r in (select * from project_games_stage) loop
        v_game_inserted     := false;
        v_platform_inserted := false;

        ------------------------------------------------------------------
        -- WALIDACJA PODSTAWOWA
        ------------------------------------------------------------------
        if r.title is null then
            v_cnt_errors := v_cnt_errors + 1;
            project_log('ERROR', 'Brak tytułu gry');
            continue;
        end if;
        
        if r.sale_month is not null
            and (r.sale_month < 1 or r.sale_month > 12) then
            v_cnt_errors := v_cnt_errors + 1;
            project_log('ERROR', 'Nieprawidłowy miesiąc sprzedaży: ' || r.sale_month);
            continue;
        end if;
                
		if r.developer is null then
            v_cnt_errors := v_cnt_errors + 1;
            project_log('ERROR', 'Brak developera dla gry: ' || r.title);
            continue;
        end if;
		
		if r.publisher is null then
            v_cnt_errors := v_cnt_errors + 1;
            project_log('ERROR', 'Brak wydawcy dla gry: ' || r.title);
            continue;
        end if;

        ------------------------------------------------------------------
        -- KONWERSJA DATY
        ------------------------------------------------------------------
        v_release_date := null;

        begin
            if r.release_date is not null then
                if regexp_like(r.release_date, '^\d{4}-\d{2}-\d{2}$') then
                    v_release_date := to_date(r.release_date, 'YYYY-MM-DD');
                elsif regexp_like(r.release_date, '^\d{1,2}\.\d{1,2}\.\d{4}$') then
                    v_release_date := to_date(r.release_date, 'DD.MM.YYYY');
                else
                    v_cnt_warnings := v_cnt_warnings + 1;
                     project_log('WARNING', 'Nieznany format daty: ' || r.release_date);
                end if;
            end if;
        exception
            when others then
                v_cnt_errors := v_cnt_errors + 1;
                project_log('ERROR', 'Błąd konwersji daty: ' || r.release_date);
                continue;
        end;

        ------------------------------------------------------------------
        -- ARCHIWIZACJA DANYCH ŹRÓDŁOWYCH
        ------------------------------------------------------------------
        insert into project_data_archive(source_type, source_name, raw_data)
        values (
            'CSV',
            'games.csv',
            json_object(
                'title' value r.title,
                'release_date' value r.release_date,
                'rating' value r.rating,
                'developer' value r.developer,
                'developer_founded_year' value r.developer_founded_year,
                'publisher' value r.publisher,
                'publisher_founded_year' value r.publisher_founded_year,
                'platform' value r.platform,
                'category' value r.category,
                'region' value r.region,
                'units_sold' value r.units_sold,
                'revenue' value r.revenue,
                'sale_year' value r.sale_year,
                'sale_month' value r.sale_month
            )
        );

        ------------------------------------------------------------------
        -- DEVELOPER
        ------------------------------------------------------------------
        begin
            select developer_id into v_dev_id
            from project_developers
            where name = r.developer;
        
            -- uzupełnienie founded_year, jeśli wcześniej był NULL
            update project_developers
            set founded_year = r.developer_founded_year
            where developer_id = v_dev_id
              and founded_year is null
              and r.developer_founded_year is not null;
        
        exception
            when no_data_found then
                insert into project_developers(name, founded_year)
                values (r.developer, r.developer_founded_year)
                returning developer_id into v_dev_id;
        end;

        ------------------------------------------------------------------
        -- PUBLISHER
        ------------------------------------------------------------------
        begin
            select publisher_id into v_pub_id
            from project_publishers
            where name = r.publisher;
        
            update project_publishers
            set founded_year = r.publisher_founded_year
            where publisher_id = v_pub_id
              and founded_year is null
              and r.publisher_founded_year is not null;
        
        exception
            when no_data_found then
                insert into project_publishers(name, founded_year)
                values (r.publisher, r.publisher_founded_year)
                returning publisher_id into v_pub_id;
        end;

        ------------------------------------------------------------------
        -- GAME
        ------------------------------------------------------------------
        begin
            select game_id into v_game_id
            from project_games
            where title = r.title
              and release_date = v_release_date;
        exception
            when no_data_found then
                insert into project_games(
                    title, release_date, rating, developer_id, publisher_id
                )
                values (
                    r.title, v_release_date, r.rating, v_dev_id, v_pub_id
                )
                returning game_id into v_game_id;
        
                v_game_inserted := true;
        end;
        
        if v_game_inserted then
            v_cnt_games_added := v_cnt_games_added + 1;
        else
            v_cnt_games_existing := v_cnt_games_existing + 1;
        end if;

        ------------------------------------------------------------------
        -- PLATFORM
        ------------------------------------------------------------------
        merge into project_platforms p
        using (select r.platform as name from dual) src
        on (p.name = src.name)
        when not matched then
            insert (name) values (src.name);

        insert into project_game_platforms (game_id, platform_id)
        select v_game_id, platform_id
        from project_platforms
        where name = r.platform
            and not exists (
                select 1
                from project_game_platforms
                where game_id = v_game_id
                    and platform_id = project_platforms.platform_id
            );
        
        if sql%rowcount = 1 then
            v_platform_inserted := true;
            v_cnt_platforms_added := v_cnt_platforms_added + 1;
        end if;

        ------------------------------------------------------------------
        -- CATEGORY
        ------------------------------------------------------------------
        merge into project_categories c
        using (select r.category as name from dual) src
        on (c.name = src.name)
        when not matched then
            insert (name) values (src.name);

        insert into project_game_categories (game_id, category_id)
        select v_game_id, category_id
        from project_categories
        where name = r.category
          and not exists (
              select 1
              from project_game_categories
              where game_id = v_game_id
                and category_id = project_categories.category_id
          );
        
        ------------------------------------------------------------------
        -- SALES
        ------------------------------------------------------------------
        if r.units_sold is not null or r.revenue is not null then
            merge into project_sales s
            using (
                select
                    v_game_id    as game_id,
                    r.region     as region,
                    r.sale_year  as sale_year,
                    r.sale_month as sale_month,
                    r.units_sold as units_sold,
                    r.revenue    as revenue
                from dual
            ) src
            on (
                s.game_id   = src.game_id
                and s.region = src.region
                and s.sale_year = src.sale_year
                and s.sale_month = src.sale_month
            )
            when not matched then
                insert (
                    game_id, region, sale_year, sale_month, units_sold, revenue
                )
                values (
                    src.game_id, src.region, src.sale_year, src.sale_month,
                    nvl(src.units_sold, 0),
                    nvl(src.revenue, 0)
                );
            
            if sql%rowcount = 1 then
                v_cnt_sales_added := v_cnt_sales_added + 1;
                project_log('INFO', 
                    'Dodano sprzedaż: ' || r.title || ', ' || r.region || ' (' || r.sale_month || '.' || r.sale_year || ')'
                );
            else
                v_cnt_sales_existing := v_cnt_sales_existing + 1;
                project_log('INFO', 
                    'Sprzedaż już istniała – pominięta: ' || r.title || ', ' || r.region || ' (' || r.sale_month || '.' || r.sale_year || ')'
                );
            end if;
        end if;

        ------------------------------------------------------------------
        -- LOG OK
        ------------------------------------------------------------------
        if v_game_inserted then
            project_log('INFO', 'Dodano nową grę: ' || r.title);
        
        elsif v_platform_inserted then
            project_log('INFO', 'Dodano nową platformę "' || r.platform || '" dla gry: ' || r.title);

        else
            project_log('INFO', 'Gra i platforma już istniały: ' || r.title || ' (' || r.platform || ')');
        end if;

    end loop;
    
    project_log(
        'INFO',
        'ETL summary: ' ||
        'new games=' || v_cnt_games_added ||
        ', existing games=' || v_cnt_games_existing ||
        ', platforms added=' || v_cnt_platforms_added ||
        ', sales added=' || v_cnt_sales_added ||
        ', sales existing=' || v_cnt_sales_existing ||
        ', warnings=' || v_cnt_warnings ||
        ', errors=' || v_cnt_errors
    );
    
    EXECUTE IMMEDIATE 'TRUNCATE TABLE project_games_stage';

exception
    when others then
        v_error_msg := SQLERRM;
        project_log('ERROR', 'ETL aborted: ' || v_error_msg);
        rollback;
        raise;
end;
/

------------------------------------------------------------------
-- procedury
------------------------------------------------------------------
create or replace procedure project_add_game (
    p_title         varchar2,
    p_release_date  date     default null,
    p_rating        number   default null,
    p_developer_id  number,
    p_publisher_id  number
) is
    v_game_id number;
    v_error_msg varchar2(4000);
begin
    if p_rating is not null and p_rating not between 0 and 100 then    
        raise_application_error(
            project_errors.c_invalid_rating,
            'Nieprawidłowy rating gry: ' || p_title
        );
    end if;

    insert into project_games (
        title, release_date, rating, developer_id, publisher_id
    )
    values (
        p_title, p_release_date, p_rating, p_developer_id, p_publisher_id
    )
    returning game_id into v_game_id;

    project_log('INFO', 'Dodano grę: ' || p_title || ' (ID=' || v_game_id || ')');

    commit;

exception
    when others then
        v_error_msg := SQLERRM;
        project_log('ERROR', 'Błąd podczas dodawania gry: ' || p_title || '. ' || v_error_msg);
        rollback;
        raise;
end;
/


create or replace procedure project_update_game_rating (
    p_game_id number,
    p_new_rating number
) is
    v_error_msg varchar2(4000);
begin
    if p_new_rating is not null and p_new_rating not between 0 and 100 then
    
        raise_application_error(
            project_errors.c_invalid_rating,
            'Nieprawidłowy rating gry'
        );
    end if;

    update project_games
    set rating = p_new_rating
    where game_id = p_game_id;

    if sql%rowcount = 0 then    
        raise_application_error(
            project_errors.c_game_not_found,
            'Gra nie istnieje ID=' || p_game_id
        );
    end if;

    project_log('INFO', 'Zaktualizowano rating gry ID=' || p_game_id);

    commit;

exception
    when others then
        v_error_msg := SQLERRM;
        project_log('ERROR', 'Błąd podczas aktualizowania gry: ' || p_game_id || '. ' || v_error_msg);
        rollback;
        raise;
end;
/

create or replace procedure project_delete_game (
    p_game_id number
) is
    v_error_msg varchar2(4000);
begin
    delete from project_games
    where game_id = p_game_id;

    if sql%rowcount = 0 then
        raise_application_error(
            project_errors.c_game_not_found,
            'Gra nie istnieje ID=' || p_game_id
        );
    end if;

    project_log('INFO', 'Usunięto grę ID=' || p_game_id);

    commit;

exception
    when others then
        v_error_msg := SQLERRM;
        project_log('ERROR', 'Błąd podczas usuwania gry: ' || p_game_id || '. ' || v_error_msg);

        rollback;
        raise;
end;
/

create or replace procedure project_build_sales_summary (
    p_period_type varchar2,   -- MONTH / QUARTER / YEAR
    p_year        number,
    p_game_id     number default null,
    p_region      varchar2 default null
) is 
    v_log_msg varchar2(4000);
begin
    -- usunięcie starych danych
    delete from project_sales_summary
    where period_type = p_period_type
      and period_year = p_year
      and (game_id = p_game_id or p_game_id is null)
      and (region = p_region or p_region is null);



    ------------------------------------------------------------------
    -- ROCZNE
    ------------------------------------------------------------------
    if p_period_type = 'YEAR' then
        insert into project_sales_summary(
            period_type,
            period_year,
            period_value,
            game_id,
            region,
            total_units,
            total_revenue,
            created_at
        )
        select
            'YEAR',
            s.sale_year,
            0,
            s.game_id,
            s.region,
            sum(s.units_sold),
            sum(s.revenue),
            systimestamp
        from project_sales s
        where s.sale_year = p_year
          and (s.game_id = p_game_id or p_game_id is null)
          and (s.region = p_region or p_region is null)
        group by s.sale_year, s.game_id, s.region;
    end if;

    ------------------------------------------------------------------
    -- KWARTALNE
    ------------------------------------------------------------------
    if p_period_type = 'QUARTER' then
        insert into project_sales_summary(
            period_type,
            period_year,
            period_value,
            game_id,
            region,
            total_units,
            total_revenue,
            created_at
        )
        select
            'QUARTER',
            s.sale_year,
            ceil(s.sale_month / 3),
            s.game_id,
            s.region,
            sum(s.units_sold),
            sum(s.revenue),
            systimestamp
        from project_sales s
        where s.sale_year = p_year
          and (s.game_id = p_game_id or p_game_id is null)
          and (s.region = p_region or p_region is null)
        group by
            s.sale_year,
            ceil(s.sale_month / 3),
            s.game_id,
            s.region;
    end if;

    ------------------------------------------------------------------
    -- MIESIĘCZNE
    ------------------------------------------------------------------
    if p_period_type = 'MONTH' then
        insert into project_sales_summary(
            period_type,
            period_year,
            period_value,
            game_id,
            region,
            total_units,
            total_revenue,
            created_at
        )
        select
            'MONTH',
            s.sale_year,
            s.sale_month,
            s.game_id,
            s.region,
            sum(s.units_sold),
            sum(s.revenue),
            systimestamp
        from project_sales s
        where s.sale_year = p_year
          and (s.game_id = p_game_id or p_game_id is null)
          and (s.region = p_region or p_region is null)
        group by
            s.sale_year,
            s.sale_month,
            s.game_id,
            s.region;
    end if;
    
    v_log_msg := 'Zbudowano podsumowanie ' || p_period_type ||
                 ' dla roku ' || p_year;

    if p_game_id is not null then
        v_log_msg := v_log_msg || ', gra ID=' || p_game_id;
    end if;

    if p_region is not null then
        v_log_msg := v_log_msg || ', region=' || p_region;
    end if;

    project_log('INFO', v_log_msg);
    commit;
end;
/

create or replace procedure project_log (
    p_event_type varchar2,
    p_message    varchar2
) is
    pragma autonomous_transaction;
begin
    insert into project_load_logs(event_type, message)
    values (p_event_type, p_message);

    commit;
end;
/


------------------------------------------------------------------
-- funkcje
------------------------------------------------------------------
create or replace function project_get_avg_rating_by_dev (
    p_developer_id number
) return number is
    v_avg number;
begin
    select nvl(avg(rating), 0)
    into v_avg
    from project_games
    where developer_id = p_developer_id;

    return v_avg;
end;
/

create or replace function project_get_game_total_revenue (
    p_game_id number
) return number is
    v_total number;
begin
    select nvl(sum(revenue), 0)
    into v_total
    from project_sales
    where game_id = p_game_id;

    return v_total;
end;
/

create or replace function project_get_game_platform_count (
    p_game_id number
) return number is
    v_cnt number;
begin
    select count(*)
    into v_cnt
    from project_game_platforms
    where game_id = p_game_id;

    return v_cnt;
end;
/

------------------------------------------------------------------
-- triggery
------------------------------------------------------------------
create or replace trigger project_trg_dev_founded_year
before insert or update on project_developers
for each row
begin
  if :new.founded_year is not null
     and :new.founded_year > extract(year from sysdate) then
    raise_application_error(
      project_errors.c_invalid_founded_year,
      'Rok założenia nie może być w przyszłości'
    );
  end if;
end;
/

create or replace trigger project_trg_pub_founded_year
before insert or update on project_publishers
for each row
begin
  if :new.founded_year is not null
     and :new.founded_year > extract(year from sysdate) then
    raise_application_error(
      project_errors.c_invalid_founded_year,
      'Rok założenia nie może być w przyszłości'
    );
  end if;
end;
/

create or replace trigger project_trg_archive_game
before delete on project_games
for each row
begin
    insert into project_data_archive (
        source_type,
        source_name,
        raw_data
    )
    values (
        'DELETE',
        'project_games',
        json_object(
            'game_id' value :old.game_id,
            'title' value :old.title,
            'release_date' value :old.release_date,
            'rating' value :old.rating,
            'developer_id' value :old.developer_id,
            'publisher_id' value :old.publisher_id
        )
    );
end;
/

create or replace trigger project_trg_sales_year
before insert or update on project_sales
for each row
declare
    v_release_year number;
begin
    select extract(year from release_date)
    into v_release_year
    from project_games
    where game_id = :new.game_id;

    if :new.sale_year < v_release_year then
        raise_application_error(
            project_errors.c_invalid_sale_year,
            'Rok sprzedaży nie może być wcześniejszy niż premiera gry'
        );
    end if;
end;
/


------------------------------------------------------------------
-- widoki
------------------------------------------------------------------
create or replace view project_v_game_sales_rank as
select
    g.title,
    sum(s.revenue) total_revenue,
    rank() over (order by sum(s.revenue) desc) revenue_rank
from project_games g
join project_sales s on s.game_id = g.game_id
group by g.title;

select * from project_v_game_sales_rank;

create or replace view project_v_region_sales_rank as
select
    s.region,
    g.title,
    sum(s.units_sold) total_units,
    dense_rank() over (
        partition by s.region
        order by sum(s.units_sold) desc
    ) region_rank
from project_sales s
join project_games g on g.game_id = s.game_id
group by s.region, g.title;

select * from project_v_region_sales_rank;

------------------------------------------------------------------
-- paczki
------------------------------------------------------------------
create or replace package project_errors is

    -- walidacja danych
    c_invalid_rating            constant number := -20001;
    c_invalid_founded_year      constant number := -20002;
    c_invalid_sale_year         constant number := -20003;
    
    -- logika biznesowa
    c_game_not_found            constant number := -20101;
end project_errors;
/