------------------------------------------------------------------
-- TWORZENIE STRUKTURY BAZY --
------------------------------------------------------------------

------------------------------------------------------------------
-- tabele słownikowe
------------------------------------------------------------------
create table project_developers (
    developer_id number generated by default as identity primary key,
    name varchar2(255) not null unique,
    founded_year number(4)
        check (founded_year > 1800)
);

create table project_publishers (
    publisher_id number generated by default as identity primary key,
    name varchar2(255) not null unique,
    founded_year number(4)
        check (founded_year > 1800)
);

create table project_platforms (
    platform_id number generated by default as identity primary key,
    name varchar2(255) not null unique
);

create table project_categories (
    category_id number generated by default as identity primary key,
    name varchar2(255) not null unique
);

------------------------------------------------------------------
-- tabela główna
------------------------------------------------------------------
create table project_games (
    game_id number generated by default as identity primary key,
    title varchar2(255) not null,
    release_date date,
    rating number(3),
        check (rating between 0 and 100),
    developer_id number references project_developers(developer_id),
    publisher_id number references project_publishers(publisher_id),
    constraint project_uk_games unique (title, release_date)
);

------------------------------------------------------------------
-- tabela sprzedaży
------------------------------------------------------------------
create table project_sales (
    sale_id number generated by default as identity primary key,
    game_id number references project_games(game_id),
    region varchar2(50),
    units_sold number 
        check (units_sold >= 0),
    revenue number(12,2) check (revenue >= 0),
    sale_year number(4)
);

alter table project_sales
add constraint project_uk_sales
unique (game_id, region, sale_year);

alter table project_sales modify (
    region not null,
    sale_year not null
);

------------------------------------------------------------------
-- tabele relacji wiele do wielu
------------------------------------------------------------------
create table project_game_platforms (
    game_id number references project_games(game_id),
    platform_id number references project_platforms(platform_id),
    constraint project_pk_game_platforms primary key (game_id, platform_id)
);

create table project_game_categories (
    game_id number references project_games(game_id),
    category_id number references project_categories(category_id),
    constraint project_pk_game_categories primary key (game_id, category_id)
);

------------------------------------------------------------------
-- archiwizacja i logowanie
------------------------------------------------------------------
create table project_data_archive (
    archive_id number generated by default as identity primary key,
    source_type varchar2(20),
    source_name varchar2(255),
    raw_data clob check (raw_data is json),
    archived_at timestamp default systimestamp
);

create table project_load_logs (
    log_id number generated by default as identity primary key,
    event_time timestamp default systimestamp,
    event_type varchar2(20),
    message varchar2(4000)
);

------------------------------------------------------------------
-- wprowadzanie danych z pliku .csv
------------------------------------------------------------------
create table project_games_stage (
    title         varchar2(255),
    release_date  varchar2(20),
    rating        number(3),
    developer     varchar2(255),
    publisher     varchar2(255),
    platform      varchar2(100),
    category      varchar2(100),
    region        varchar2(50),
    units_sold    number,
    revenue       number(12,2),
    sale_year     number(4)
);

create or replace procedure project_load_games_etl is
    v_dev_id        project_developers.developer_id%type;
    v_pub_id        project_publishers.publisher_id%type;
    v_game_id       project_games.game_id%type;
    v_release_date  date;
    
    v_game_status   varchar2(20);
    
    v_cnt_inserted_games number := 0;
    v_cnt_inserted_sales number := 0;
    v_cnt_skipped_games  number := 0;
    v_cnt_skipped_sales  number := 0;
    v_cnt_warnings number := 0;
    v_cnt_errors   number := 0;
    
    v_error_msg varchar2(4000);
begin
    for r in (select * from project_games_stage) loop
        v_game_status := null;

        ------------------------------------------------------------------
        -- WALIDACJA PODSTAWOWA
        ------------------------------------------------------------------
        if r.title is null then
            v_cnt_errors := v_cnt_errors + 1;
            insert into project_load_logs(event_type, message)
            values ('ERROR', 'Brak tytułu gry');
            continue;
        end if;
        
        if r.rating is not null and (r.rating < 0 or r.rating > 100) then
            v_cnt_errors := v_cnt_errors + 1;
            insert into project_load_logs(event_type, message)
            values ('ERROR', 'Nieprawidłowy rating dla gry: ' || r.title);
            continue;
        end if;
                
		if r.developer is null then
            v_cnt_warnings := v_cnt_warnings + 1;
            insert into project_load_logs(event_type, message)
            values ('WARNING', 'Brak developera');
            continue;
        end if;
		
		if r.publisher is null then
            v_cnt_warnings := v_cnt_warnings + 1;
            insert into project_load_logs(event_type, message)
            values ('WARNING', 'Brak wydawcy');
            continue;
        end if;

        ------------------------------------------------------------------
        -- KONWERSJA DATY
        ------------------------------------------------------------------
        v_release_date := null;

        begin
            if r.release_date is not null then
                if regexp_like(r.release_date, '^\d{4}-\d{2}-\d{2}$') then
                    v_release_date := to_date(r.release_date, 'YYYY-MM-DD');
                elsif regexp_like(r.release_date, '^\d{1,2}\.\d{1,2}\.\d{4}$') then
                    v_release_date := to_date(r.release_date, 'DD.MM.YYYY');
                else
                    v_cnt_warnings := v_cnt_warnings + 1;
                    insert into project_load_logs(event_type, message)
                    values ('WARNING', 'Nieznany format daty: ' || r.release_date);
                end if;
            end if;
        exception
            when others then
                v_cnt_errors := v_cnt_errors + 1;
                insert into project_load_logs(event_type, message)
                values ('ERROR', 'Błąd konwersji daty: ' || r.release_date);
                continue;
        end;

        ------------------------------------------------------------------
        -- ARCHIWIZACJA DANYCH ŹRÓDŁOWYCH
        ------------------------------------------------------------------
        insert into project_data_archive(source_type, source_name, raw_data)
        values (
            'CSV',
            'games.csv',
            json_object(
                'title' value r.title,
                'release_date' value r.release_date,
                'rating' value r.rating,
                'developer' value r.developer,
                'publisher' value r.publisher,
                'platform' value r.platform,
                'category' value r.category,
                'region' value r.region,
                'units_sold' value r.units_sold,
                'revenue' value r.revenue,
                'sale_year' value r.sale_year
            )
        );

        ------------------------------------------------------------------
        -- DEVELOPER
        ------------------------------------------------------------------
        begin
            select developer_id into v_dev_id
            from project_developers
            where name = r.developer;
        exception
            when no_data_found then
                insert into project_developers(name)
                values (r.developer)
                returning developer_id into v_dev_id;
        end;

        ------------------------------------------------------------------
        -- PUBLISHER
        ------------------------------------------------------------------
        begin
            select publisher_id into v_pub_id
            from project_publishers
            where name = r.publisher;
        exception
            when no_data_found then
                insert into project_publishers(name)
                values (r.publisher)
                returning publisher_id into v_pub_id;
        end;

        ------------------------------------------------------------------
        -- GAME
        ------------------------------------------------------------------
        begin
            select game_id into v_game_id
            from project_games
            where title = r.title
              and release_date = v_release_date;
        
            v_game_status := 'SKIPPED';
        exception
            when no_data_found then
                insert into project_games(
                    title, release_date, rating, developer_id, publisher_id
                )
                values (
                    r.title, v_release_date, r.rating, v_dev_id, v_pub_id
                )
                returning game_id into v_game_id;
        
                v_game_status := 'INSERTED';
        end;

        ------------------------------------------------------------------
        -- PLATFORM
        ------------------------------------------------------------------
        merge into project_platforms p
        using (select r.platform as name from dual) src
        on (p.name = src.name)
        when not matched then
            insert (name) values (src.name);

        insert into project_game_platforms (game_id, platform_id)
        select v_game_id, platform_id
        from project_platforms
        where name = r.platform
          and not exists (
              select 1
              from project_game_platforms
              where game_id = v_game_id
                and platform_id = project_platforms.platform_id
          );

        ------------------------------------------------------------------
        -- CATEGORY
        ------------------------------------------------------------------
        merge into project_categories c
        using (select r.category as name from dual) src
        on (c.name = src.name)
        when not matched then
            insert (name) values (src.name);

        insert into project_game_categories (game_id, category_id)
        select v_game_id, category_id
        from project_categories
        where name = r.category
          and not exists (
              select 1
              from project_game_categories
              where game_id = v_game_id
                and category_id = project_categories.category_id
          );
        
        ------------------------------------------------------------------
        -- SALES
        ------------------------------------------------------------------
        if r.units_sold is not null or r.revenue is not null then
            merge into project_sales s
            using (
                select
                    v_game_id    as game_id,
                    r.region     as region,
                    r.sale_year  as sale_year,
                    r.units_sold as units_sold,
                    r.revenue    as revenue
                from dual
            ) src
            on (
                s.game_id   = src.game_id
                and s.region = src.region
                and s.sale_year = src.sale_year
            )
            when not matched then
                insert (
                    game_id, region, sale_year, units_sold, revenue
                )
                values (
                    src.game_id, src.region, src.sale_year,
                    nvl(src.units_sold, 0),
                    nvl(src.revenue, 0)
                );
            
            if sql%rowcount = 1 then
                v_cnt_inserted_sales := v_cnt_inserted_sales + 1;
                insert into project_load_logs(event_type, message)
                values (
                    'INFO',
                    'Dodano sprzedaż: ' || r.title || ', ' || r.region || ', ' || r.sale_year
                );
            else
                v_cnt_skipped_sales := v_cnt_skipped_sales + 1;
                insert into project_load_logs(event_type, message)
                values (
                    'INFO',
                    'Sprzedaż już istniała – pominięta: ' || r.title || ', ' || r.region || ', ' || r.sale_year
                );
            end if;
        end if;

        ------------------------------------------------------------------
        -- LOG OK
        ------------------------------------------------------------------
        if v_game_status = 'INSERTED' then
            v_cnt_inserted_games := v_cnt_inserted_games + 1;
            insert into project_load_logs(event_type, message)
            values (
                'INFO',
                'Dodano nową grę: ' || r.title || ' (' || r.platform || ')'
            );
        elsif v_game_status = 'SKIPPED' then
            v_cnt_skipped_games := v_cnt_skipped_games + 1;
            insert into project_load_logs(event_type, message)
            values (
                'INFO',
                'Gra już istniała – pominięta: ' || r.title || ' (' || r.platform || ')'
            );
        end if;

    end loop;
    
    insert into project_load_logs(event_type, message)
    values (
        'INFO',
        'ETL summary: inserted games=' || v_cnt_inserted_games ||
        ', inserted sales=' || v_cnt_inserted_sales ||
        ', skipped games=' || v_cnt_skipped_games ||
        ', skipped sales=' || v_cnt_skipped_sales ||
        ', warnings=' || v_cnt_warnings ||
        ', errors=' || v_cnt_errors
    );

    commit;
    
    --EXECUTE IMMEDIATE 'TRUNCATE TABLE project_games_stage';

exception
    when others then
        v_error_msg := sqlerrm;
        insert into project_load_logs(event_type, message)
        values (
            'ERROR',
            'ETL aborted: ' || v_error_msg
        );
        rollback;
        raise;
end;
/


------------------------------------------------------------------
-- triggery
------------------------------------------------------------------
create or replace trigger trg_dev_founded_year
before insert or update on project_developers
for each row
begin
  if :new.founded_year is not null
     and :new.founded_year > extract(year from sysdate) then
    raise_application_error(
      -20001,
      'Rok założenia nie może być w przyszłości'
    );
  end if;
end;
/

create or replace trigger trg_pub_founded_year
before insert or update on project_publishers
for each row
begin
  if :new.founded_year is not null
     and :new.founded_year > extract(year from sysdate) then
    raise_application_error(
      -20001,
      'Rok założenia nie może być w przyszłości'
    );
  end if;
end;
/