------------------------------------------------------------------
-- TWORZENIE STRUKTURY BAZY --
------------------------------------------------------------------

------------------------------------------------------------------
-- tabele słownikowe
------------------------------------------------------------------
create table project_developers (
    developer_id number generated by default as identity primary key,
    name varchar2(255) not null unique,
    founded_year number(4)
        check (founded_year  between 1800 and extract(year from sysdate))
);

create table project_publishers (
    publisher_id number generated by default as identity primary key,
    name varchar2(255) not null unique,
    founded_year number(4)
        check (founded_year  between 1800 and extract(year from sysdate))
);

create table project_platforms (
    platform_id number generated by default as identity primary key,
    name varchar2(255) not null unique
);

create table project_categories (
    category_id number generated by default as identity primary key,
    name varchar2(255) not null unique
);

------------------------------------------------------------------
-- tabela główna
------------------------------------------------------------------
create table project_games (
    game_id number generated by default as identity primary key,
    title varchar2(255) not null,
    release_date date,
    rating number(3),
        check (rating between 0 and 100),
    developer_id number references project_developers(developer_id),
    publisher_id number references project_publishers(publisher_id),
    constraint project_uk_games unique (title, release_date)
);

------------------------------------------------------------------
-- tabela sprzedaży
------------------------------------------------------------------
create table project_sales (
    sale_id number generated by default as identity primary key,
    game_id number references project_games(game_id),
    region varchar2(50),
    units_sold number 
        check (units_sold >= 0),
    revenue number(12,2) check (revenue >= 0),
    sale_year number(4)
);

------------------------------------------------------------------
-- tabele relacji wiele do wielu
------------------------------------------------------------------
create table project_game_platforms (
    game_id number references project_games(game_id),
    platform_id number references project_platforms(platform_id),
    constraint project_pk_game_platforms primary key (game_id, platform_id)
);

create table project_game_categories (
    game_id number references project_games(game_id),
    category_id number references project_categories(category_id),
    constraint project_pk_game_categories primary key (game_id, category_id)
);

------------------------------------------------------------------
-- archiwizacja i logowanie
------------------------------------------------------------------
create table project_data_archive (
    archive_id number generated by default as identity primary key,
    source_type varchar2(20),
    source_name varchar2(255),
    raw_data clob check (raw_data is json),
    archived_at timestamp default systimestamp
);

create table project_load_logs (
    log_id number generated by default as identity primary key,
    event_time timestamp default systimestamp,
    event_type varchar2(20),
    message varchar2(4000)
);

------------------------------------------------------------------
-- wprowadzanie danych z pliku .csv
------------------------------------------------------------------
create table project_games_stage (
    title varchar2(255),
    release_date varchar2(20),
    developer varchar2(255),
    publisher varchar2(255),
    platform varchar2(100),
    category varchar2(100)
);

CREATE OR REPLACE PROCEDURE project_load_games_etl IS
    v_dev_id        project_developers.developer_id%TYPE;
    v_pub_id        project_publishers.publisher_id%TYPE;
    v_game_id       project_games.game_id%TYPE;
    v_release_date  DATE;
BEGIN
    FOR r IN (SELECT * FROM project_games_stage) LOOP

        ------------------------------------------------------------------
        -- WALIDACJA PODSTAWOWA
        ------------------------------------------------------------------
        IF r.title IS NULL THEN
            INSERT INTO project_load_logs(event_type, message)
            VALUES ('ERROR', 'Brak tytułu gry');
            CONTINUE;
        END IF;

        ------------------------------------------------------------------
        -- KONWERSJA DATY (JEDYNE MIEJSCE TO_DATE)
        ------------------------------------------------------------------
        v_release_date := NULL;

        BEGIN
            IF r.release_date IS NOT NULL THEN
                IF REGEXP_LIKE(r.release_date, '^\d{4}-\d{2}-\d{2}$') THEN
                    v_release_date := TO_DATE(r.release_date, 'YYYY-MM-DD');
                ELSIF REGEXP_LIKE(r.release_date, '^\d{1,2}\.\d{1,2}\.\d{4}$') THEN
                    v_release_date := TO_DATE(r.release_date, 'DD.MM.YYYY');
                ELSE
                    INSERT INTO project_load_logs(event_type, message)
                    VALUES ('WARNING', 'Nieznany format daty: ' || r.release_date);
                END IF;
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                INSERT INTO project_load_logs(event_type, message)
                VALUES ('ERROR', 'Błąd konwersji daty: ' || r.release_date);
                CONTINUE;
        END;

        ------------------------------------------------------------------
        -- ARCHIWIZACJA DANYCH ŹRÓDŁOWYCH
        ------------------------------------------------------------------
        INSERT INTO project_data_archive(source_type, source_name, raw_data)
        VALUES (
            'CSV',
            'games.csv',
            JSON_OBJECT(
                'title' VALUE r.title,
                'release_date' VALUE r.release_date,
                'developer' VALUE r.developer,
                'publisher' VALUE r.publisher,
                'platform' VALUE r.platform,
                'category' VALUE r.category
            )
        );

        ------------------------------------------------------------------
        -- DEVELOPER
        ------------------------------------------------------------------
        BEGIN
            SELECT developer_id INTO v_dev_id
            FROM project_developers
            WHERE name = r.developer;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO project_developers(name)
                VALUES (r.developer)
                RETURNING developer_id INTO v_dev_id;
        END;

        ------------------------------------------------------------------
        -- PUBLISHER
        ------------------------------------------------------------------
        BEGIN
            SELECT publisher_id INTO v_pub_id
            FROM project_publishers
            WHERE name = r.publisher;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO project_publishers(name)
                VALUES (r.publisher)
                RETURNING publisher_id INTO v_pub_id;
        END;

        ------------------------------------------------------------------
        -- GAME
        ------------------------------------------------------------------
        BEGIN
            SELECT game_id INTO v_game_id
            FROM project_games
            WHERE title = r.title
              AND release_date = v_release_date;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO project_games(
                    title, release_date, developer_id, publisher_id
                )
                VALUES (
                    r.title, v_release_date, v_dev_id, v_pub_id
                )
                RETURNING game_id INTO v_game_id;
        END;

        ------------------------------------------------------------------
        -- PLATFORM
        ------------------------------------------------------------------
        MERGE INTO project_platforms p
        USING (SELECT r.platform AS name FROM dual) src
        ON (p.name = src.name)
        WHEN NOT MATCHED THEN
            INSERT (name) VALUES (src.name);

        INSERT INTO project_game_platforms (game_id, platform_id)
        SELECT v_game_id, platform_id
        FROM project_platforms
        WHERE name = r.platform
          AND NOT EXISTS (
              SELECT 1
              FROM project_game_platforms
              WHERE game_id = v_game_id
                AND platform_id = project_platforms.platform_id
          );

        ------------------------------------------------------------------
        -- CATEGORY
        ------------------------------------------------------------------
        MERGE INTO project_categories c
        USING (SELECT r.category AS name FROM dual) src
        ON (c.name = src.name)
        WHEN NOT MATCHED THEN
            INSERT (name) VALUES (src.name);

        INSERT INTO project_game_categories (game_id, category_id)
        SELECT v_game_id, category_id
        FROM project_categories
        WHERE name = r.category
          AND NOT EXISTS (
              SELECT 1
              FROM project_game_categories
              WHERE game_id = v_game_id
                AND category_id = project_categories.category_id
          );

        ------------------------------------------------------------------
        -- LOG OK
        ------------------------------------------------------------------
        INSERT INTO project_load_logs(event_type, message)
        VALUES ('INFO', 'Załadowano grę: ' || r.title || ', ' || 'na ' || r.platform);

    END LOOP;

    COMMIT;
END;
/

